version: '3.7'

services:
  django: &django
    image: geekbeacon/django_new:devel
    build:
      context: .
#      dockerfile: ./compose/production/django/Dockerfile
#    depends_on:
#      - postgres
#      - rabbit
    env_file: .env
    ports:
        - 8000:8000
#    command: /gunicorn.sh
